/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'fetch-trending-videos': EventHandler<never, never>
    'SubmitChannel': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'yt.submit'; data: never }>
    'ResolveChannel': EventHandler<never, { topic: 'yt.channel.resolved'; data: never }>
    'FetchLatest-5-videos': EventHandler<never, { topic: 'yt.videos.fetched'; data: never }>
    'fetch-niche': EventHandler<never, { topic: 'yt.niche.fetched'; data: never }>
  }
}