/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'fetch-trending-videos': EventHandler<never, { topic: 'paidUser.trendVid.success'; data: never }>
    'SubmitChannel': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'yt.submit'; data: never }>
    'send-email-with-titles': EventHandler<never, { topic: 'yt.titles.Email-Send.error'; data: never }>
    'ResolveChannel': EventHandler<never, { topic: 'yt.channel.resolved'; data: never } | { topic: 'yt.channel.error'; data: never }>
    'FetchLatest-10-videos': EventHandler<never, { topic: 'paidUser.videosfetched.success'; data: never }>
    'fetch-niche': EventHandler<never, { topic: 'yt.niche.fetched'; data: never } | { topic: 'yt.niche.error'; data: never }>
    'Error-handling': EventHandler<never, never>
    'fetch-optimized-titles': EventHandler<never, { topic: 'yt.AI-Title.fetched'; data: never } | { topic: 'yt.AI-Title.error'; data: never }>
    'Fetch-Niche': EventHandler<never, { topic: 'paidUser.Nichefetched.success'; data: never }>
    'PaidUser-VerifyPayment': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'paidUser.payment.success'; data: never }>
    'email final metadata ': EventHandler<never, never>
    'PaidUser-CreateOrder': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'fetch-AI-optimized metadata': EventHandler<never, { topic: 'paidUser.AImetadata.success'; data: never }>
  }
}