import BackHomeButton from "@/components/BackHomeButton";

export default function TermsPage() {
  const currentDate = new Date().toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
  });

  return (
    <main className="w-full flex justify-center px-4 py-10">
      <div className="w-full max-w-3xl text-[15px] sm:text-base leading-relaxed">
        <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
        <p className="text-sm text-gray-500 mb-6">Last updated: {currentDate}</p>

        <p className="mb-4">
          ReachAI provides AI-powered YouTube metadata such as optimized titles,
          descriptions, tags and hashtags. Using ReachAI means you agree to these
          terms.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2">Service Limitations</h2>
        <p className="mb-4">
          AI output may suggest optimizations but we do not guarantee views,
          rankings, subscribers, watch time, or revenue.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2">Acceptable Use</h2>
        <p className="mb-4">
          You agree not to misuse, spam, reverse engineer, or damage the platform,
          or submit illegal or harmful content.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2">Payments</h2>
        <p className="mb-4">
          Payments are processed securely via Razorpay. We do not store card, UPI,
          or bank details.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2">Ownership</h2>
        <p className="mb-4">
          Metadata generated by AI belongs to you. Platform logic, prompts,
          design, and systems belong to ReachAI.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2">Liability</h2>
        <p className="mb-4">
          We are not responsible for business loss, channel strikes, copyright
          issues, or damages. Use the service at your own risk.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2">Changes</h2>
        <p className="mb-4">
          We may update or modify features and terms anytime.
        </p>

        <p className="mt-6">
          Need help? Use the{" "}
          <a href="/contact" className="text-blue-600 underline">
            Contact page
          </a>.
        </p>


<div className="flex items-center justify-center mt-4">
<BackHomeButton/>
</div>



      </div>
    </main>
  );
}
